In [1]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X, y = make_blobs(n_samples=200, centers=3, n_features=3)

df = pd.DataFrame(dict(x=X[:,0], y=X[:,1], label=y))
print("Top five Records\n")
print(df.head(5))

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.40, random_state=0)

model = LogisticRegression()
model.fit(X_train, y_train)

predicted = model.predict(X_test)

print("\nClassification Report")
print(classification_report(y_test, predicted))

Top five Records

          x         y  label
0 -1.790081 -5.280265      0
1 -2.334785 -5.168811      0
2 -4.600144  2.725745      1
3 -3.886808 -6.361812      0
4 -5.577517  3.601039      1

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        29

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [3]:
 import numpy as np
from sklearn.linear_model import Lasso

x = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])

y = np.array([3,5,7,9,11])

model = Lasso()

model.fit(x, y)

print("Intercept :", model.intercept_)
print("Coefficients :", model.coef_)
 
print("\nPredicted values:")
print(model.predict(x))

print("\nR^2 score :", model.score(x, y))

Intercept : 2.5
Coefficients : [1.5 0. ]

Predicted values:
[ 4.   5.5  7.   8.5 10. ]

R^2 score : 0.9375


In [4]:
import numpy as np
from sklearn.linear_model import Ridge
x = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])
y = np.array([3,5,7,9,1])
model = Ridge(alpha=0.1)
model.fit(x,y)
print("Intercept :", model.intercept_)
print("Coefficient:", model.coef_)
print("\nPredicted values :")
print(model.predict (x))
print("\nR^2 Sore:", model.score(x,y))
             

Intercept : 5.0
Coefficient: [0. 0.]

Predicted values :
[5. 5. 5. 5. 5.]

R^2 Sore: 0.0


In [5]:
import numpy as np
from sklearn.linear_model import ElasticNet

x = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])

y = np.array([3,5,7,9,11])

model = ElasticNet(alpha=0.1, l1_ratio=0.5)

model.fit(x, y)

print("Intercept :", model.intercept_)
print("Coefficient :", model.coef_)

print("\nPredicted values:")
print(model.predict(x))

print("\nR^2 Score:", model.score(x, y))

Intercept : 0.1745433194399144
Coefficient : [0.97719665 0.97346668]

Predicted values:
[ 3.09867333  5.04933667  7.          8.95066333 10.90132667]

R^2 Score: 0.9993914733212926


In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

x = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])

y = np.array([3,5,7,9,11])

model = LinearRegression()
model.fit(x, y)

predicted = model.predict(x)

print("Predicted values:")
print(predicted)

print("\nMSE :", mean_squared_error(y, predicted))

Predicted values:
[ 3.  5.  7.  9. 11.]

MSE : 0.0


In [8]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

x = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])

y = np.array([3,5,7,9,11])

model = LinearRegression()
model.fit(x, y)

predicted = model.predict(x)

print("Predicted values:")
print(predicted)

print("\nMAE :", mean_absolute_error(y, predicted))

Predicted values:
[ 3.  5.  7.  9. 11.]

MAE : 0.0
